# Generated by Django 3.1.6 on 2021-09-27 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialedTimer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
