# Generated by Django 3.1.6 on 2021-09-28 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialedTimer', '0002_auto_20210902_1807'),
        ('dialedTimer', '0002_auto_20210927_1512'),
    ]

    operations = [
    ]
